Fix Issue #28:  mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame (#29)
* 🥅 Fix issue #28: catch mutagen.mp3.HeaderNotFoundError while loading podcasts

* this prevents app crash because of single broken/incompatible mp3 files.

* 🥅 Fix "ValueError: year 0 is out of range" error when trying to format date tag as into html

* 🐛 fix UnicodeEncodeError by allowing surrogates in the data while encoding to bytes

* e.g. the following:
     UnicodeEncodeError: 'utf-8' codec can't encode character '\udc84' in position 767364: surrogates not allowed
* ensure request responses are already encoded to bytes to avoid strict encoding by the requests library

* 🔊 add logging for broken file metadata (HeaderNotFoundError)